### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by marked80** [samartzidis/magicstick.io#1]
Hi samartzidis, 

Love your projects! Until now I have been using Raspikey with my (not fully supported) A1843 keyboard to be able to use it for my Mac and Windows computer connected to the same screen (using the screens usb hub). Is magicstick maybe a better solution for this and would it work on Mac too regarding the battery level etc?
If so I will order one right away :)

Thanks in advance for your reply.

**Comment by samartzidis** [comment]
Hi @marked80, thanks for your good words! :)

magicstick.io is a better solution because it works (boots up) instantly since it is a microcontroller-based device. It also supports both wired and wireless keyboard connection modes (Raspikey was only wireless). Unfortunately, I do not have an A1843 keyboard to guarantee that it will 100% work with it, but since Raspikey worked with the A1843, magicstick.io will most likely work too (as they share some code). Plus, if I am not mistaken A1843 is the same Magic Keyboard generation as the A1644 but in full size.

Regarding the battery level indicator, it will not currently work on a Mac (that is, if you connect raspikey.io to a Mac) but once you switch it back to the Windows connection it will work, provided that you have the magicstick.io tray utility installed on Windows. I could make the battery level indicator work out of the box on Mac too, but I never imagined that use case, to be honest!

I also suggest this option. If you send me an e-mail, I can arrange to send you one for free so that you can see if it works for you.

**Comment by marked80** [comment]
Hi George,

Thanks for your reply, I would love to try if it works for my usecase ofcourse. I do it like this because I have a work controlled windows laptop where I cannot install software on and also cannot use Bluetooth but wanted to be able to share my Mac keyboard with my Mac and this laptop (mouse is separate but that doesn’t really matter)

So let me know what to do then we can arrange some testing ☺️. I am pretty tech savvy so if I need to do some tinkering myself it won’t be a problem.

Kind regards Mark.

Op 23 feb 2024 om 19:18 heeft George Samartzidis ***@***.***> het volgende geschreven:

﻿

Hi @marked80<https://github.com/marked80>, thanks for your good words! :)

magicstick.io is a better solution because it works (boots up) instantly since it is a microcontroller-based device. It also supports both wired and wireless keyboard connection modes (Raspikey was only wireless). Unfortunately, I do not have an A1843 keyboard to guarantee that it will 100% work with it, but since Raspikey worked with the A1843, magicstick.io will most likely work too (as they share some code). Plus, if I am not mistaken A1843 is the same Magic Keyboard generation as the A1644 but in full size.

Regarding the battery level indicator, it will not currently work on a Mac (that is, if you connect raspikey.io to a Mac) but once you switch it back to the Windows connection it will work, provided that you have the magicstick.io tray utility installed on Windows. I could make the battery level indicator work out of the box on Mac too, but I never imagined that use case, to be honest!

I also suggest this option. If you send me an e-mail, I can arrange to send you one for free so that you can see if it works for you.

**Comment by samartzidis** [comment]
Hi, @marked80. Sorry, I was not clear! Please send me an e-mail directly at: _samartzidis@gmail.com_. Cheers!
