### ISSUE TITLE
Feature: swap ctrl and command

### ISSUE THREAD

**Issue by farcaller** [samartzidis/magicstick.io#10]
Didn't realize it's not an option, but to me it sounds like the most obvious choice. Many standard hotkeys between mac and windows share the same letter while utilizing ctrl on the latter and cmd on the former. Would be nice to be able to swap these.

**Comment by samartzidis** [comment]
Provided you update your firmware to v2, you can achieve that by adding these rules at the end of the default keymap configuration:
```
(mod & KEYBOARD_MODIFIER_LEFTCTRL) && set_mod((mod & ~KEYBOARD_MODIFIER_LEFTCTRL) | KEYBOARD_MODIFIER_LEFTGUI):end
(mod & KEYBOARD_MODIFIER_LEFTGUI) && set_mod((mod & ~KEYBOARD_MODIFIER_LEFTGUI) | KEYBOARD_MODIFIER_LEFTCTRL):end
```

**Comment by farcaller** [comment]
For posteriority, it seems that the complete answer is:

```
((mod & KEYBOARD_MODIFIER_LEFTCTRL) && !(mod & KEYBOARD_MODIFIER_LEFTGUI)) && set_mod((mod & ~KEYBOARD_MODIFIER_LEFTCTRL) | KEYBOARD_MODIFIER_LEFTGUI):end
((mod & KEYBOARD_MODIFIER_LEFTGUI) && !(mod & KEYBOARD_MODIFIER_LEFTCTRL)) && set_mod((mod & ~KEYBOARD_MODIFIER_LEFTGUI) | KEYBOARD_MODIFIER_LEFTCTRL):end
```

otherwise win+ctrl+xxx shortcuts break.

**Comment by samartzidis** [comment]
@farcaller thanks for pointing this out.

It's trickier than I thought :)

I think that the ideal expression for dealing with keystroke modifiers swaps like this would be:

`(mod & KEYBOARD_MODIFIER_LEFTCTRL != 0) ^ (mod & KEYBOARD_MODIFIER_LEFTGUI != 0) && set_mod(mod ^ (KEYBOARD_MODIFIER_LEFTCTRL | KEYBOARD_MODIFIER_LEFTGUI))`

Which should also be placed at the beginning of the default ruleset (but after line 1!) plus you do not want an "end", as if the rule matches and performs a modifiers swap, you still want to continue processing the next rules in the list (since these are modifier keys and most likely used in various other key combinations).

The rule says: IF <kbd>Left Ctrl</kbd> is pressed OR <kbd>Left Command</kbd> is pressed - but not both at the same time (thus the XOR ^ operator), THEN (the &&) perform a bit swap (of the KEYBOARD_MODIFIER_LEFTCTRL and KEYBOARD_MODIFIER_LEFTGUI bits) using the XOR operator.
