### ISSUE TITLE
Feature: Reconfigure right option as FN

### ISSUE THREAD

**Issue by Omnicrash** [samartzidis/magicstick.io#4]
Being able to reconfigure right-option to FN would be very useful for using shortcuts such as HOME/END/PGUP/PGDN.

**Comment by samartzidis** [comment]
You cannot assign another key to function straight as <kbd>Fn</kbd>, but you can repurpose any key (in v2+) including <kbd>right option</kbd> + "any key" combinations to do anything you want, so I will consider this closed since you can still achieve what you said.

E.g. you can map <kbd>right option</kbd>+<kbd>left</kbd> to <kbd>home</kbd> etc.
